#: schema node_modules/wrangler/config-schema.json
name = "server"
main = "index.ts"
compatibility_date = "2025-09-24"
compatibility_flags = [ "nodejs_compat" ]

workers_dev = true

[[durable_objects.bindings]]
name = "GroceriesDurableObjects"
class_name = "GroceriesDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GroceriesDurableObject"]

[observability]
enabled = true